#CS438 MP1 Makefile
#by Yumen Tsao

CC = gcc
INC = -I. -Ilibs
FLAGS = -O0 -Wall -Wextra -Werror -Wno-unused -Wno-sign-compare -g -std=gnu99 -pthread
DFLAG=

all: reliable_sender reliable_receiver

reliable_sender: sender_main.c
	$(CC) $(FLAGS) $(INC) $^ -o $@

reliable_receiver: receiver_main.c
	$(CC) $(FLAGS) $(INC) $^ -o $@

clean:
	$(RM) -r *.o reliable_sender reliable_receiver